## PRODUCTION PROFILE CONFIGURATION ##
#
# This file is included when the 'pro' spring profile is selected
##

#Hibernate
spring:
  jpa:
    hibernate:
      ddl-auto: validate

#Logging
logging:
  level:
    com:
      aljumaro:
        techtest: ERROR

#Custom
profileName: Production